name: "Run tests"
description: "A composite action to run all our tests and check that we don't have problems in our git."

inputs:
  dotnet-version:
    description: "The dotnet version to use to run our tests"
    required: true

runs:
  using: "composite"

  defaults:
    run:
      shell: bash

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - id: run-script
      run: echo "result=Success" >> $GITHUB_OUTPUT
