name: Run tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Use my composite dotnet install action
      uses: ./.github/actions/setup-dotnet
      with:
        node-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
