name: Run tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use my composite dotnet install action
      uses: ./.github/actions/run-tests
      with:
        node-version: '8.0.x'
